### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by kputnam** [kputnam/piggly#22]
Piggly calls `fork` in several places, but this call fails on Windows.  The win32 gem doesn't emulate the call sufficiently, so the best option is to avoid forking on Windows.

**Comment by kputnam** [comment]
@RussellKeane I don't have a Windows machine to develop with, and it's been quite a while since I've worked on this project, so I'm not in a good position to fix this.

If you're willing to contribute a PR that works on Windows, I can check that it still works on UNIX and merge it, and I'll be happy to help you work on this if you're interested. I don't remember where (or why) `fork` is used, but that's the cause of the incompatibility.

**Comment by RucialK** [comment]
Hi,

I don't think this is an issue (see https://github.com/kputnam/piggly/issues/24)

It seems to be working under windows at the moment.

**Comment by kputnam** [comment]
OK, thanks for the confirmation!
