### ISSUE TITLE
use of select filter

### ISSUE THREAD

**Issue by born-in-brooklyn** [kputnam/piggly#32]
Hi,

With the most recent release a technique that I used to use to filter out only certain procedures for running piggly seems to have gotten broken. I used to do something like this:

```
piggly trace -s myschema.someproc -s myschema.some_other_proc
```

and it used to process only those procs. now it seems it only processes the first one. any ideas?

**Comment by kputnam** [comment]
Hi @born-in-brooklyn, sorry this took a while to address. I think this broke about a year ago in efc196c51c1c941e7fea6d442627561de56becb4, which was my fault for not having tests that would've caught it.

I reverted the code and wrote some tests to specify how `-r` and`-s` work, so you should be all set. (@dbut023, I assumed the intent of your change was to make the code clearer and not to change the functionality, but feel free to shoot me a message and we can work your change back in)

**Comment by kputnam** [comment]
I also published a new gem that includes the fix

**Comment by born-in-brooklyn** [comment]
No worries for the delay! I'm glad you are continuing to support this. Right now my main goal is to use this to report coverage on a legacy project, so I don't want to analyze everything, just what has already been refactored. I will give it a try and get back to you. Thanks again!
