### ISSUE TITLE
error installing piggly gem on windows

### ISSUE THREAD

**Issue by born-in-brooklyn** [kputnam/piggly#35]
this doesn't appear to have ill effects (yet) but figured Id report it;

```
$ gem install piggly
unable to convert "\xA3" from ASCII-8BIT to UTF-8 for lib/piggly/reporter/resour                                                   ces/sortable.js, skipping
Successfully installed piggly-2.2.2
Parsing documentation for piggly-2.2.2
Installing ri documentation for piggly-2.2.2
Done installing documentation for piggly after 2 seconds
1 gem installed
```

**Comment by kputnam** [comment]
Hmm, this [looks like](https://stackoverflow.com/questions/15807535/unable-to-convert-x90-from-ascii-8bit-to-utf-8-for-bin-wkhtmltopdf-linux-386) an issue with code in RubyGems or `rdoc` when generating documentation. If you're willing, can you try `gem update rdoc` and then reinstalling to see if that fixes it?

I don't have access to a Windows machine to check myself. If you don't want to bother with it, no big deal -- it seems harmless and should only affect the locally installed documentation (whatever that happens to be).

**Comment by born-in-brooklyn** [comment]
sure

**Comment by born-in-brooklyn** [comment]
nope, same problem:
```
foo@bar MINGW64 /c/Users/foo/blech/baz/src/test/resources/sql/piggly (develop)
$ gem update --force rdoc
(eval):3: warning: string literal in condition
(eval):2: warning: string literal in condition
Updating installed gems
Updating rdoc
Successfully installed rdoc-5.1.0
Parsing documentation for rdoc-5.1.0
Installing ri documentation for rdoc-5.1.0
Installing darkfish documentation for rdoc-5.1.0
Done installing documentation for rdoc after 17 seconds
Parsing documentation for rdoc-5.1.0
Done installing documentation for rdoc after 6 seconds
Gems updated: rdoc

foo@bar MINGW64 /c/Users/foo/blech/baz/src/test/resources/sql/piggly (develop)
$ gem uninstall piggly

foo@bar MINGW64 /c/Users/foo/blech/baz/src/test/resources/sql/piggly (develop)
$ gem install piggly
unable to convert "\xA3" from ASCII-8BIT to UTF-8 for lib/piggly/reporter/resources/sortable.js, skipping
Successfully installed piggly-2.2.2
Parsing documentation for piggly-2.2.2
Installing ri documentation for piggly-2.2.2
Done installing documentation for piggly after 2 seconds
1 gem installed
```

**Comment by born-in-brooklyn** [comment]
also, the report only seems to produce output for the first 23 stored procedures

**Comment by kputnam** [comment]
Ok, looks like the stray characters in that JavaScript file weren't important so I've just removed them (it was used to detect currency formats in a table, to sort data numerically). Can you open a separate issue about missing output in the report? I probably will need more details before I can work on that one -- how many procedures did it say were compiled and traced on the console, etc?

**Comment by born-in-brooklyn** [comment]
yeah, scratch that. I was pumping in bad params :(

**Comment by kputnam** [comment]
No problem :-)

**Comment by born-in-brooklyn** [comment]
hang on though, have more bugs concerning procs

**Comment by born-in-brooklyn** [comment]
and thanks again for your help with this. Is there a way I can support you in this?

**Comment by kputnam** [comment]
Oh, you're welcome! Submitting bug reports or patches or documentation is enough support for me. Since I rarely use PL/pgSQL (and even Ruby) these days, it's great to get help from others. Thank you for asking :-)

**Comment by born-in-brooklyn** [comment]
I was referring to donations!

**Comment by kputnam** [comment]
Ah, you are very kind. If you wish, you can make a donation to the Cystic Fibrosis Foundation on my wife's page: http://fightcf.cff.org/goto/shuchi-and-kyle (her page from last year was here fightcf.cff.org/goto/kyle2017).

Best wishes,
-- Kyle
